In [52]:
import pandas as pd
import numpy as np

In [53]:
data = {
    'movie': ['Movie A', 'Movie B', 'Movie C', 'Movie D'],
    'Action': [1, 0, 1, 1],
    'Comedy': [0, 1, 1, 0],
    'Drama': [1, 1, 0, 1]
}
df = pd.DataFrame(data)

In [54]:
print(df)

     movie  Action  Comedy  Drama
0  Movie A       1       0      1
1  Movie B       0       1      1
2  Movie C       1       1      0
3  Movie D       1       0      1


In [55]:
features=df[['Action','Comedy','Drama']].values

In [56]:
print(features)
print(type(features))
print(features.shape)

[[1 0 1]
 [0 1 1]
 [1 1 0]
 [1 0 1]]
<class 'numpy.ndarray'>
(4, 3)


In [57]:
features[0]

array([1, 0, 1], dtype=int64)

In [58]:
def cosine_similarity(v1,v2):
    dot_product=np.dot(v1,v2)
    norm_v1=np.linalg.norm(v1)
    norm_v2=np.linalg.norm(v2)
    result= dot_product/(norm_v1*norm_v2)
    return result


In [59]:
def compute_cosine(features):
    num_items=features.shape[0]
    similarity_matrix=np.zeros((num_items,num_items))
    for i in range(num_items):
        for j in range(num_items):
            similarity_matrix[i,j]=cosine_similarity(features[i],features[j])

    return similarity_matrix        

In [60]:
cosine_sim_matrix=compute_cosine(features)
print(cosine_sim_matrix)

[[1.  0.5 0.5 1. ]
 [0.5 1.  0.5 0.5]
 [0.5 0.5 1.  0.5]
 [1.  0.5 0.5 1. ]]


In [61]:
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=df['movie'], columns=df['movie'])
print("Cosine Similarity Matrix:\n", cosine_sim_df)

Cosine Similarity Matrix:
 movie    Movie A  Movie B  Movie C  Movie D
movie                                      
Movie A      1.0      0.5      0.5      1.0
Movie B      0.5      1.0      0.5      0.5
Movie C      0.5      0.5      1.0      0.5
Movie D      1.0      0.5      0.5      1.0


In [62]:
def recommmend_movie(movie_name,similarity_matrix,recommend=2):
    similar_scores=similarity_matrix.loc[movie_name]
    print(similar_scores)
    print('-------')
    sorted_movies=similar_scores.sort_values(ascending=False)
    print(sorted_movies)
    print('-------')
    recommedations=sorted_movies.index[1:recommend+1]
    print(recommedations.tolist())
    return recommedations
recommend_movies=recommmend_movie('Movie A',cosine_sim_df)
print("Recommended Movies for 'Movie A':", recommend_movies)

movie
Movie A    1.0
Movie B    0.5
Movie C    0.5
Movie D    1.0
Name: Movie A, dtype: float64
-------
movie
Movie A    1.0
Movie D    1.0
Movie B    0.5
Movie C    0.5
Name: Movie A, dtype: float64
-------
['Movie D', 'Movie B']
Recommended Movies for 'Movie A': Index(['Movie D', 'Movie B'], dtype='object', name='movie')
